model:
  _target_: pl_bolts.models.rl.DQN
  env: "Breakout-v0"
  network:
    _target_: pl_bolts.models.rl.common.networks.CNN
trainer:
  accelerator: "cpu"
  gpus: '0'
log_video: True
log_video_path: "video"
logger:
  project: "project"
  entity: "skoltech_ml2022_project_synced_target_nets"