model:
  _target_: pl_bolts.models.rl.dueling_dqn_model.DuelingDQN
  env: "DemonAttack-v0"
  batch_size: 64
  min_episode_reward: 0
trainer:
  accelerator: "gpu"
  gpus: [0,]
log_video: True
log_video_path: "video"
logger:
  project: "project"
  entity: "skoltech_ml2022_project_synced_target_nets"