model:
  _target_: models.SyncedTargetNetworkDQN
  env: "Pong-v0"
  network:
    _target_: pl_bolts.models.rl.common.networks.CNN
trainer:
  accelerator: "cpu"
log_video: True
log_video_path: "video"
logger:
  project: "skoltech_ml_project"
  entity: "penchekrak"