model:
  _target_: models.PLDQN
  env: "Pong-v0"
  network:
    _target_: networks.SmallCNN
trainer:
  accelerator: "gpu"
  gpus: '0'
log_video: True
log_video_path: "video"
logger:
  project: "project"
  entity: "skoltech_ml2022_project_synced_target_nets"